### ISSUE TITLE
AS a user, I WANT a deployed dashboard, SO THAT the dasboard is accessible from a public URL.

### ISSUE THREAD

**Issue by frankpiva** [mike-menendez/205-group-project#3]
Start thinking about how to deploy the dashboard; Heroku, AWS, private server? It would be interesting if we could figure out what the stress tolerance of free solutions are in case our project goes viral. Maybe we can incorporate system information into an admin tab on the dashboard?

**Comment by mike-menendez** [comment]
Front end will be static resources deployed via storage. If you prefer AWS as that is what you are familiar with, S3 behind an ELB with SSL term enabled. Ideally the same cloud as where the back end lives. I'm fine with all the major ones. The only limitation on this will be that they will not be able to use flask templates (which templates aren't ideal any ways and with this small of a site, I'd prefer static assets to minimize load server side).
